# Generated by Django 4.1.7 on 2023-03-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=25, null=True)),
                ('zip', models.CharField(max_length=10, null=True)),
                ('phone', models.CharField(default='xxx-xxx-xxxx', max_length=10)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('note', models.TextField()),
                ('favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
